export const REGISTRATION_PENDING = "REGISTRATION_PENDING";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const ADD_CONTACT = "ADD_CONTACT";

export const UPDATE_CHATS = "UPDATE_CHATS";
export const ADD_CHATS = "ADD_CHATS";
export const REMOVE_CHATS = "REMOVE_CHATS";
export const ACTIVE_CHAT = "ACTIVE_CHAT";
export const CLEAR_ALL_CHATS = "CLEAR_ALL_CHATS";
export const UPDATE_CHAT_MEMBERS = "UPDATE_CHAT_MEMBERS";
export const UPDATE_CHAT_DETAILS = "UPDATE_CHAT_DETAILS";

export const ADD_MESSAGE = "ADD_MESSAGE";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

export const GO_TO_CHAT = "GO_TO_CHAT";
export const GO_TO_CONTACTS = "GO_TO_CONTACTS";
export const GO_TO_NOTIFICATIONS = "GO_TO_NOTIFICATIONS";
export const GO_TO_PROFILE = "GO_TO_PROFILE";

export const LOGOUT_PENDING = "LOGOUT_PENDING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
